exports.GENRES = [
  { id: 1, name: 'american' },
  { id: 2, name: 'asian' },
  { id: 3, name: 'bakery' },
  { id: 4, name: 'belgian' },
  { id: 5, name: 'bistro' },
  { id: 6, name: 'british' },
  { id: 7, name: 'cafe' },
  { id: 8, name: 'coffee' },
  { id: 9, name: 'contemporary' },
  { id: 10, name: 'continental' },
  { id: 11, name: 'eclectic' },
  { id: 12, name: 'european' },
  { id: 13, name: 'french' },
  { id: 14, name: 'fusion' },
  { id: 15, name: 'grill' },
  { id: 16, name: 'hawaiian' },
  { id: 17, name: 'international' },
  { id: 18, name: 'irish' },
  { id: 19, name: 'italian' },
  { id: 20, name: 'japanese' },
  { id: 21, name: 'kosher' },
  { id: 22, name: 'oysters' },
  { id: 23, name: 'pacific rim' },
  { id: 24, name: 'pasta' },
  { id: 25, name: 'polynesian' },
  { id: 26, name: 'sandwiches' },
  { id: 27, name: 'seafood' },
  { id: 28, name: 'steak' },
  { id: 29, name: 'sushi' },
  { id: 30, name: 'tea' },
  { id: 31, name: 'traditional' },
  { id: 32, name: 'vegetarian' },
  { id: 33, name: 'vietnamese' },
];
