exports.STATES = [
  { id: 1, fullName: 'alabama', name: 'AL' },
  { id: 2, fullName: 'alaska', name: 'AK' },
  { id: 3, fullName: 'arizona', name: 'AZ' },
  { id: 4, fullName: 'arkansas', name: 'AR' },
  { id: 5, fullName: 'california', name: 'CA' },
  { id: 6, fullName: 'colorado', name: 'CO' },
  { id: 7, fullName: 'connecticut', name: 'CT' },
  { id: 8, fullName: 'delaware', name: 'DE' },
  { id: 9, fullName: 'florida', name: 'FL' },
  { id: 10, fullName: 'georgia', name: 'GA' },
  { id: 11, fullName: 'hawaii', name: 'HI' },
  { id: 12, fullName: 'idaho', name: 'ID' },
  { id: 13, fullName: 'illinois', name: 'IL' },
  { id: 14, fullName: 'indiana', name: 'IN' },
  { id: 15, fullName: 'iowa', name: 'IA' },
  { id: 16, fullName: 'kansas', name: 'KS' },
  { id: 17, fullName: 'kentucky', name: 'KY' },
  { id: 18, fullName: 'louisiana', name: 'LA' },
  { id: 19, fullName: 'maine', name: 'ME' },
  { id: 20, fullName: 'maryland', name: 'MD' },
  { id: 21, fullName: 'massachusetts', name: 'MA' },
  { id: 22, fullName: 'michigan', name: 'MI' },
  { id: 23, fullName: 'minnesota', name: 'MN' },
  { id: 24, fullName: 'mississippi', name: 'MS' },
  { id: 25, fullName: 'missouri', name: 'MO' },
  { id: 26, fullName: 'montana', name: 'MT' },
  { id: 27, fullName: 'nebraska', name: 'NE' },
  { id: 28, fullName: 'nevada', name: 'NV' },
  { id: 29, fullName: 'new hampshire', name: 'NH' },
  { id: 30, fullName: 'new jersey', name: 'NJ' },
  { id: 31, fullName: 'new mexico', name: 'NM' },
  { id: 32, fullName: 'new york', name: 'NY' },
  { id: 33, fullName: 'north carolina', name: 'NC' },
  { id: 34, fullName: 'north dakota', name: 'ND' },
  { id: 35, fullName: 'ohio', name: 'OH' },
  { id: 36, fullName: 'oklahoma', name: 'OK' },
  { id: 37, fullName: 'oregon', name: 'OR' },
  { id: 38, fullName: 'pennsylvania', name: 'PA' },
  { id: 39, fullName: 'rhode island', name: 'RI' },
  { id: 40, fullName: 'south carolina', name: 'SC' },
  { id: 41, fullName: 'south dakota', name: 'SD' },
  { id: 42, fullName: 'tennessee', name: 'TN' },
  { id: 43, fullName: 'texas', name: 'TX' },
  { id: 44, fullName: 'utah', name: 'UT' },
  { id: 45, fullName: 'vermont', name: 'VT' },
  { id: 46, fullName: 'virginia', name: 'VA' },
  { id: 47, fullName: 'washington', name: 'WA' },
  { id: 48, fullName: 'west virginia', name: 'WV' },
  { id: 49, fullName: 'wisconsin', name: 'WI' },
  { id: 50, fullName: 'wyoming', name: 'WY' },
];
